### PR TITLE
Add Docker scripts.

### PR DESCRIPTION
**Pull request by ryan-clancy**
The only caveat is that the Anserini jar must be copied into the root directory of this repo due to the relative path of `../Anserini` being outside of the build context of the Dockerfile.

### CODE REVIEW

**Comment by lintool** [comment]
hey @r-clancy I'm looking at this - I'm wondering why we need all the stopwords list from languages we don't use?

**Comment by ryan-clancy** [comment]
@lintool Mentioned in Slack, but just so it's here, it looks like Solr expects the files to be part of the config or it throws exceptions.

Just a note that Anserini should be built from the `docker-twitter` branch (until that is merged) for this to work.

**Comment by lintool** [comment]
I've followed instructions and confirmed this works. One minor tweak:

```$ docker exec solr ./load.sh
rm: can't remove '/mb11/write.lock': No such file or directory
```

Fix, and then we're good to merge.

Change script to rm only if the file exists...

**Review by lintool — APPROVED** [review]
changes to load script requested, otherwise lgtm.

**Pull request merged**
